- data: 2018-8-22 周三
  posUrl: mineJobSearch.html
  comUrl: mineCorRes.html

- data: 2018-8-28 周六
  posUrl: mineJobSearch.html
  comUrl: mineCorRes.html

- data: 2018-8-22 周三
  posUrl: mineJobSearch.html
  comUrl: mineCorRes.html